src/Entity/Medecin.php
<?php

namespace App\Entity;

use App\Repository\MedecinRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Nullable;

#[ORM\Entity(repositoryClass: MedecinRepository::class)]
class Medecin extends User
{
   
    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse_cabinet = null;

    #[ORM\Column(length: 255)]
    private ?string $fixe = null;

    #[ORM\Column(length: 255)]
    private ?string $diplome_formation = null;

    #[ORM\Column]
    private ?float $tarif = null;

    #[ORM\Column]
    private ?bool $cnam = null;

   
    

    #[ORM\OneToMany(mappedBy: 'medecin', targetEntity: Article::class)]
    private Collection $articles;

    #[ORM\ManyToOne(inversedBy: 'medecin')]
    private ?Specialites $specialites = null;

    #[ORM\OneToMany(mappedBy: 'medecin', targetEntity: Consulation::class)]
    private Collection $consulations;

    #[ORM\OneToMany(mappedBy: 'medecin', targetEntity: RendezVous::class)]
    private Collection $rendezVouses;

    #[ORM\OneToMany(mappedBy: 'medecin', targetEntity: Images::class)]
    private Collection $imagesCabinet;

    #[ORM\OneToMany(mappedBy: 'medecin', targetEntity: Dossier::class)]
    private Collection $dossiers;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->consulations = new ArrayCollection();
        $this->rendezVouses = new ArrayCollection();
        $this->imagesCabinet = new ArrayCollection();
        $this->dossiers = new ArrayCollection();
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAdresseCabinet(): ?string
    {
        return $this->adresse_cabinet;
    }

    public function setAdresseCabinet(string $adresse_cabinet): self
    {
        $this->adresse_cabinet = $adresse_cabinet;

        return $this;
    }

    public function getFixe(): ?string
    {
        return $this->fixe;
    }

    public function setFixe(string $fixe): self
    {
        $this->fixe = $fixe;

        return $this;
    }

    public function getDiplomeFormation(): ?string
    {
        return $this->diplome_formation;
    }

    public function setDiplomeFormation(string $diplome_formation): self
    {
        $this->diplome_formation = $diplome_formation;

        return $this;
    }

    public function getTarif(): ?float
    {
        return $this->tarif;
    }

    public function setTarif(float $tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function isCnam(): ?bool
    {
        return $this->cnam;
    }

    public function setCnam(bool $cnam): self
    {
        $this->cnam = $cnam;

        return $this;
    }

    
   

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setMedecin($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getMedecin() === $this) {
                $article->setMedecin(null);
            }
        }

        return $this;
    }

    public function getSpecialites(): ?Specialites
    {
        return $this->specialites;
    }

    public function setSpecialites(?Specialites $specialites): self
    {
        $this->specialites = $specialites;

        return $this;
    }

    /**
     * @return Collection<int, Consulation>
     */
    public function getConsulations(): Collection
    {
        return $this->consulations;
    }

    public function addConsulation(Consulation $consulation): self
    {
        if (!$this->consulations->contains($consulation)) {
            $this->consulations->add($consulation);
            $consulation->setMedecin($this);
        }

        return $this;
    }

    public function removeConsulation(Consulation $consulation): self
    {
        if ($this->consulations->removeElement($consulation)) {
            // set the owning side to null (unless already changed)
            if ($consulation->getMedecin() === $this) {
                $consulation->setMedecin(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RendezVous>
     */
    public function getRendezVouses(): Collection
    {
        return $this->rendezVouses;
    }

    public function addRendezVouse(RendezVous $rendezVouse): self
    {
        if (!$this->rendezVouses->contains($rendezVouse)) {
            $this->rendezVouses->add($rendezVouse);
            $rendezVouse->setMedecin($this);
        }

        return $this;
    }

    public function removeRendezVouse(RendezVous $rendezVouse): self
    {
        if ($this->rendezVouses->removeElement($rendezVouse)) {
            // set the owning side to null (unless already changed)
            if ($rendezVouse->getMedecin() === $this) {
                $rendezVouse->setMedecin(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImagesCabinet(): Collection
    {
        return $this->imagesCabinet;
    }

    public function addImagesCabinet(Images $imagesCabinet): self
    {
        if (!$this->imagesCabinet->contains($imagesCabinet)) {
            $this->imagesCabinet->add($imagesCabinet);
            $imagesCabinet->setMedecin($this);
        }

        return $this;
    }

    public function removeImagesCabinet(Images $imagesCabinet): self
    {
        if ($this->imagesCabinet->removeElement($imagesCabinet)) {
            // set the owning side to null (unless already changed)
            if ($imagesCabinet->getMedecin() === $this) {
                $imagesCabinet->setMedecin(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Dossier>
     */
    public function getDossiers(): Collection
    {
        return $this->dossiers;
    }

    public function addDossier(Dossier $dossier): self
    {
        if (!$this->dossiers->contains($dossier)) {
            $this->dossiers->add($dossier);
            $dossier->setMedecin($this);
        }

        return $this;
    }
    

    public function removeDossier(Dossier $dossier): self
    {
        if ($this->dossiers->removeElement($dossier)) {
            // set the owning side to null (unless already changed)
            if ($dossier->getMedecin() === $this) {
                $dossier->setMedecin(null);
            }
        }

        return $this;
    }
 
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Doctrine\ORM\Mapping\InheritanceType;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[InheritanceType('JOINED')]
#[DiscriminatorColumn(name: 'Type', type: 'string')]
#[DiscriminatorMap(['user' => User::class, 'admin' => Admin::class,'patient'=>Patient::class,'assistant'=>Assistant::class ,'medecin'=>Medecin::class])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column]
    private ?int $cin = null;

    #[ORM\Column(length: 255)]
    private ?string $sexe = null;

    #[ORM\Column]
    private ?int $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $gouvernorat = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;
    /**
     * @Assert\EqualTo(propertyPath = "password",
     * message="Vous n'avez pas saisi le même mot de passe !" )
     */
    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private $confirm_password=null;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Commentaire::class)]
    private Collection $commentaires;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Reclamation::class)]
    private Collection $reclamations;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Images::class)]
    private Collection $images;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ArticleLike::class)]
    private Collection $articleLikes;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ArticleFavorie::class)]
    private Collection $articleFavories;


   
  

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->reclamations = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->articleLikes = new ArrayCollection();
        $this->articleFavories = new ArrayCollection();
     
     
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

   

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
         return $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
       
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getConfirmPassword()
    {
      return $this->confirm_password;
    }
    public function setConfirmPassword($confirm_password)
    {
    $this->confirm_password = $confirm_password;
    return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCin(): ?int
    {
        return $this->cin;
    }

    public function setCin(int $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getGouvernorat(): ?string
    {
        return $this->gouvernorat;
    }

    public function setGouvernorat(string $gouvernorat): self
    {
        $this->gouvernorat = $gouvernorat;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setUtilisateur($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUtilisateur() === $this) {
                $commentaire->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reclamation>
     */
    public function getReclamations(): Collection
    {
        return $this->reclamations;
    }

    public function addReclamation(Reclamation $reclamation): self
    {
        if (!$this->reclamations->contains($reclamation)) {
            $this->reclamations->add($reclamation);
            $reclamation->setUtilisateur($this);
        }

        return $this;
    }

    public function removeReclamation(Reclamation $reclamation): self
    {
        if ($this->reclamations->removeElement($reclamation)) {
            // set the owning side to null (unless already changed)
            if ($reclamation->getUtilisateur() === $this) {
                $reclamation->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setUser($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getUser() === $this) {
                $image->setUser(null);
            }
        }

        return $this;
    }
    public function __toString(): string{
        return (string)$this->nom;
       }

    /**
     * @return Collection<int, ArticleLike>
     */
    public function getArticleLikes(): Collection
    {
        return $this->articleLikes;
    }

    public function addArticleLike(ArticleLike $articleLike): self
    {
        if (!$this->articleLikes->contains($articleLike)) {
            $this->articleLikes->add($articleLike);
            $articleLike->setUser($this);
        }

        return $this;
    }

    public function removeArticleLike(ArticleLike $articleLike): self
    {
        if ($this->articleLikes->removeElement($articleLike)) {
            // set the owning side to null (unless already changed)
            if ($articleLike->getUser() === $this) {
                $articleLike->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ArticleFavorie>
     */
    public function getArticleFavories(): Collection
    {
        return $this->articleFavories;
    }

    public function addArticleFavory(ArticleFavorie $articleFavory): self
    {
        if (!$this->articleFavories->contains($articleFavory)) {
            $this->articleFavories->add($articleFavory);
            $articleFavory->setUser($this);
        }

        return $this;
    }

    public function removeArticleFavory(ArticleFavorie $articleFavory): self
    {

templates/medecin/_delete_form.html.twig
<form method="post" action="{{ path('app_medecin_delete', {'id': medecin.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ medecin.id) }}">
    <button class="btn">Delete</button>
</form>

templates/medecin/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/medecin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Medecin{% endblock %}

{% block body %}
    <h1>Edit Medecin</h1>

    {{ include('medecin/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_medecin_index') }}">back to list</a>

    {{ include('medecin/_delete_form.html.twig') }}
{% endblock %}

templates/medecin/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Medecin index{% endblock %}

{% block body %}
    <h1>Medecin index</h1>

    <table class="table">
        <thead>
            <tr>
             
                <th>Email</th>
               
                <th>Nom</th>
                <th>Prenom</th>
         
                <th>Telephone</th>
                <th>Gouvernorat</th>
                <th>Adresse</th>
              
                <th>Titre</th>
                <th>Adresse_cabinet</th>
           
              
                <th>Tarif</th>
              
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for medecin in medecins %}
            <tr>
                <td>{{ medecin.id }}</td>
                <td>{{ medecin.email }}</td>
                <td>{{ medecin.roles ? medecin.roles|json_encode : '' }}</td>
                <td>{{ medecin.password }}</td>
                <td>{{ medecin.nom }}</td>
                <td>{{ medecin.prenom }}</td>
                <td>{{ medecin.cin }}</td>
                <td>{{ medecin.sexe }}</td>
                <td>{{ medecin.telephone }}</td>
                <td>{{ medecin.gouvernorat }}</td>
                <td>{{ medecin.adresse }}</td>
                <td>{{ medecin.confirmPassword }}</td>
                <td>{{ medecin.titre }}</td>
                <td>{{ medecin.adresseCabinet }}</td>
                <td>{{ medecin.fixe }}</td>
                <td>{{ medecin.diplomeFormation }}</td>
                <td>{{ medecin.tarif }}</td>
                <td>{{ medecin.cnam ? 'Yes' : 'No' }}</td>
                <td>{{ medecin.horraireOuverture ? medecin.horraireOuverture|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_medecin_show', {'id': medecin.id}) }}">show</a>
                    <a href="{{ path('app_medecin_edit', {'id': medecin.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="20">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_medecin_new') }}">Create new</a>
{% endblock %}

templates/medecin/medecin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Medecins
{% endblock %}

{% block content %}
	<div class="page-wrapper">
		<div class="content container-fluid pb-0">
			<h4 class="mb-3"></h4>
			<div class="row">
				<div class="col-xl-12 col-sm-12 col-12">
					<div class="card">
						<div class="card-header">
							<div class="row align-items-center">
								<div class="col">
									<h5 class="card-title">Doctors</h5>
								</div>
								<div class="col-auto d-flex flex-wrap">
									<div class="form-custom me-2">
										<div id="tableSearch" class="dataTables_wrapper"></div>
									</div>
									<div class="multipleSelection">
										<div class="selectBox">
											<p class="mb-0 me-2">
												<i class="feather-filter me-1"></i>
												Filter By
												                                                    Speciality
											</p>
											<span class="down-icon">
												<i class="feather-chevron-down"></i>
											</span>
										</div>
										<div id="checkBoxes">
											<form>
												<p class="lab-title">Specialities</p>
												<div class="selectBox-cont">
													<label class="custom_check w-100">
														<input type="checkbox" name="year" checked>
														<span class="checkmark"></span>
														Urology
													</label>
													<label class="custom_check w-100">
														<input type="checkbox" name="year">
														<span class="checkmark"></span>
														Neurology
													</label>
													<label class="custom_check w-100">
														<input type="checkbox" name="year">
														<span class="checkmark"></span>
														Orthopedic
													</label>
													<label class="custom_check w-100">
														<input type="checkbox" name="year">
														<span class="checkmark"></span>
														Cardiologist
													</label>
													<label class="custom_check w-100">
														<input type="checkbox" name="year">
														<span class="checkmark"></span>
														Dentist
													</label>
													<label class="custom_check w-100">
														<input type="checkbox" name="year">
														<span class="checkmark"></span>
														Gynacologist
													</label>
													<label class="custom_check w-100">
														<input type="checkbox" name="year">
														<span class="checkmark"></span>
														Pediatrist
													</label>
													<label class="custom_check w-100">
														<input type="checkbox" name="year">
														<span class="checkmark"></span>
														Orthopedic
													</label>
												</div>
												<button type="submit" class="btn w-100 btn-primary">Apply</button>
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="card">

							<div class="card-body">
								<table class="table datatable-basic table table-borderless hover-table" id="datatable">
									<thead class="thead-light">
										<th>Nom</th>
										<th>Prenom</th>
										<th>Telephone</th>
										<th>Gouvernorat</th>
										<th>Adresse</th>
										<th>Titre</th>
										<th>Adresse_cabinet</th>
										<th>Tarif</th>
										<th>Actions</th>
									</thead>
									<tbody>

										{% for medecin in medecins %}
											<tr>

												<td>{{ medecin.nom }}</td>
												<td>{{ medecin.prenom }}</td>

												<td>{{ medecin.telephone }}</td>
												<td>{{ medecin.gouvernorat }}</td>
												<td>{{ medecin.adresse }}</td>
												<td>{{ medecin.titre }}</td>
												<td>{{ medecin.adresseCabinet }}</td>

												<td>{{ medecin.tarif }}</td>
												<td>
													<a href="{{ path('app_medecin_show', {'id': medecin.id}) }}">show</a>
													<a href="{{ path('app_medecin_edit', {'id': medecin.id}) }}">edit</a>
												</td>
											</tr>
										{% else %}
											<tr>
												<td colspan="20">no records found</td>
											</tr>
										{% endfor %}
									</tbody>
								</table>

							</div>
						</div>
					</div>
				{% endblock %}

templates/medecin/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Medecin{% endblock %}

{% block body %}
    <h1>Medecin</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ medecin.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ medecin.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ medecin.roles ? medecin.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ medecin.password }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ medecin.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ medecin.prenom }}</td>
            </tr>
            <tr>
                <th>Cin</th>
                <td>{{ medecin.cin }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ medecin.sexe }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ medecin.telephone }}</td>
            </tr>
            <tr>
                <th>Gouvernorat</th>
                <td>{{ medecin.gouvernorat }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ medecin.adresse }}</td>
            </tr>
            <tr>
                <th>Confirm_password</th>
                <td>{{ medecin.confirmPassword }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ medecin.titre }}</td>
            </tr>
            <tr>
                <th>Adresse_cabinet</th>
                <td>{{ medecin.adresseCabinet }}</td>
            </tr>
            <tr>
                <th>Fixe</th>
                <td>{{ medecin.fixe }}</td>
            </tr>
            <tr>
                <th>Diplome_formation</th>
                <td>{{ medecin.diplomeFormation }}</td>
            </tr>
            <tr>
                <th>Tarif</th>
                <td>{{ medecin.tarif }}</td>
            </tr>
            <tr>
                <th>Cnam</th>
                <td>{{ medecin.cnam ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Horraire_ouverture</th>
                <td>{{ medecin.horraireOuverture ? medecin.horraireOuverture|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_medecin_index') }}">back to list</a>

    <a href="{{ path('app_medecin_edit', {'id': medecin.id}) }}">edit</a>

    {{ include('medecin/_delete_form.html.twig') }}
{% endblock %}